// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import VibrationCardController from "./vibration_card_controller"
application.register("vibration-card", VibrationCardController)

import VibrationFormController from "./vibration_form_controller"
application.register("vibration-form", VibrationFormController)
